### ISSUE TITLE
Dependency order is not implied

### ISSUE THREAD

**Issue by eterps** [chrisdebruin/hal-json-api#1]
Hi @chrisdebruin 

In app.rb:11 The require statements are based on file glob order (which is highly OS, filesystem & storage device dependent).

In my case I get:

```
bundle exec rake db:migrate
rake aborted!
NameError: uninitialized constant Presenter::Like
./hal-json-api/app/presenters/likes.rb:10:in `<module:Likes>'
./hal-json-api/app/presenters/likes.rb:2:in `<module:Presenter>'
./hal-json-api/app/presenters/likes.rb:1:in `<top (required)>'
./hal-json-api/app.rb:11:in `block in <top (required)>'
./hal-json-api/app.rb:11:in `each'
./hal-json-api/app.rb:11:in `<top (required)>'
./hal-json-api/Rakefile:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)
```

**Comment by chrisdebruin** [comment]
Ok that sucks, fixed it. Tested it on a ubuntu machine works for me now

**Comment by eterps** [comment]
:+1:
